// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjz_xe6i_gFxH1kJFqBHzvPLDJ7tcVvWs',
    appId: '1:992213462471:web:45b32afe5191445d1a3de2',
    messagingSenderId: '992213462471',
    projectId: 'test-5c420',
    authDomain: 'test-5c420.firebaseapp.com',
    databaseURL: 'https://test-5c420-default-rtdb.firebaseio.com',
    storageBucket: 'test-5c420.firebasestorage.app',
    measurementId: 'G-YCM5DQSG6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWorsmMXhZE091cyoKRS2xCnO2IedRSWQ',
    appId: '1:992213462471:android:e6e0a6ed0b71d5821a3de2',
    messagingSenderId: '992213462471',
    projectId: 'test-5c420',
    databaseURL: 'https://test-5c420-default-rtdb.firebaseio.com',
    storageBucket: 'test-5c420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA35ByZtZ6DfCFCIpbW-aH6wk3Z4Yuac9s',
    appId: '1:992213462471:ios:7d4f6bc37479e6b71a3de2',
    messagingSenderId: '992213462471',
    projectId: 'test-5c420',
    databaseURL: 'https://test-5c420-default-rtdb.firebaseio.com',
    storageBucket: 'test-5c420.firebasestorage.app',
    iosBundleId: 'com.example.zonalertNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TU_MACOS_API_KEY',
    appId: 'TU_MACOS_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'TU_PROJECT_ID',
    storageBucket: 'TU_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.movilesZonalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TU_WINDOWS_API_KEY',
    appId: 'TU_WINDOWS_APP_ID',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID',
    projectId: 'TU_PROJECT_ID',
    authDomain: 'TU_PROJECT_ID.firebaseapp.com',
    storageBucket: 'TU_PROJECT_ID.appspot.com',
  );
}